language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
#- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn clean install sonar:sonar -Dsonar.organization=ca.mcgill.ecse428:foodme -Dsonar.host.url=http://sonarcloud.io -Dsonar.login=3f8a7d76841c33434d4a9a81f676bce1d9a5b6a8 -Dsonar.jacoco.reportPaths=target/jacoco.exec -Dmaven.test.failure.ignore=true
#- mvn clean install sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=207f5a26d2633a63916fd94354f3c3aeb6941ef3 -Dsonar.jacoco.reportPaths=target/jacoco.exec -Dmaven.test.failure.ignore=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
